### PR TITLE
Update to @cnakazawa/watch to get rid of the 'merge' package

### PR DESCRIPTION
**Pull request by cpojer**
See #134 and #135.

I missed this change in `watch` originally: https://github.com/cpojer/watch/commit/5ac469084c5edb1ab75d428b457099cef1e3d210

The tests are now passing locally, sorry for not verifying earlier, my bad :(

### CODE REVIEW

**Comment by cpojer** [comment]
cc @stefanpenner

**Comment by stefanpenner** [comment]
verifying now

**Comment by stefanpenner** [comment]
LGTM, thank you!

**Comment by stefanpenner** [comment]
released as v4.0.3 🎉

**Pull request merged**
