### PR TITLE
remove fsevents

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
Spoke with @amasad in person yesterday this can be safely removed, as the original use-case (from jest) has taken a different approach. 

If users are having FS watching issues, OSX's filewatching is pretty sad, we strongly recommend they utilize watchman.

**Comment by stefanpenner** [comment]
released as v4.0.0 🎉

**Comment by wtgtybhertgeghgtwtg** [comment]
Is there a reason `fsevents` is left as an optional dependency?

**Comment by stefanpenner** [comment]
released as v4.0.1 🎉

**Comment by SimenB** [comment]
>the original use-case (from jest) has taken a different approach.

Question, what is that approach? Jest currently uses the `FSEventsWatcher` removed in this PR: https://github.com/facebook/jest/blob/d0e627cb974af0c85c93befb914a45f8c57e5bac/packages/jest-haste-map/src/index.js#L684-L689

**Comment by SimenB** [comment]
ping @stefanpenner.

**Comment by SimenB** [comment]
Any chance of reverting this? We have to vendor the previous solution in Jest (due to https://github.com/facebook/jest/issues/8088, https://github.com/facebook/jest/pull/8258). I don't know what the motivation for removing it was, but v2 of `fsevents` uses napi, so should be less of a pain for consumers if that was part of it

**Comment by stefanpenner** [comment]
I’ll take a look once I return of vacation. If you don’t hear from me by next week, it may have gotten dropped. Feel free to reping

**Comment by SimenB** [comment]
@stefanpenner ping 😀

**Comment by SimenB** [comment]
@stefanpenner any news here?

**Comment by SimenB** [comment]
@stefanpenner 2020 ping 🎆

**Pull request merged**
