### PR TITLE
CLI

### LINKED ISSUE #44: Can it be used with Command line ?
I have to get it running as a task inside NPM build scripts.

If it possible ?

### PR DESCRIPTION
**Pull request by m-allanson**
Add a command line interface to sane.  

Resolves #44.

### CODE REVIEW

**Comment by amasad** [comment]
great, thanks!

**Comment by amasad** [comment]
published in v1.0.4

**Comment by m-allanson** [comment]
Nice one! :+1:

**Comment by amasad** [comment]
@m-allanson  Been using the cli myself and just wanted to say thank you again. It's a great addition!

**Comment by m-allanson** [comment]
No problem, thanks for sane!

**Pull request merged**
